version: '3'
services:
  force-model:
    image: xdyngrpc-python
    command: model.py
    working_dir: /work
    volumes:
      - .:/work
    user: ${CURRENT_UID}
  xdyn:
    image: xdyn
    working_dir: /data
    entrypoint: >
      wait-for-it force-model:9002 -s -t 20 --
      xdyn-for-cs xdyn.yml --dt 0.1 -g -p 9002
    volumes:
      - .:/data
    user: ${CURRENT_UID}
    depends_on:
      - force-model
    environment:
      - no_proxy
  test:
    image: xdyngrpc-python
    command: tests.py
    working_dir: /work
    volumes:
      - .:/work
    user: ${CURRENT_UID}
    depends_on:
      - xdyn
    environment:
      - no_proxy
